/*
  # Add comprehensive aviation shortcuts

  1. Changes
    - Insert new aviation shortcuts with their meanings
    - Preserves existing shortcuts
    - Adds new shortcuts in alphabetical order

  2. Notes
    - Uses ON CONFLICT DO NOTHING to avoid duplicates
    - Maintains data integrity
*/

INSERT INTO shortcuts (shortcut, meaning)
VALUES
  ('AAP', 'AFT Attendant Panel'),
  ('ABP', 'Able Bodied Passenger'),
  ('A/C', 'Aircraft'),
  ('ACARS', 'Aircraft Communications Addressing and Reporting System'),
  ('ACL', 'Aircraft Cabin Log'),
  ('ACP', 'Attendant Control Panel / Area Call Panel (A320NEO)'),
  ('AED', 'Automated External Defibrillator'),
  ('AFL', 'Aircraft Flight Log'),
  ('AIP', 'Additional Indication Panel'),
  ('ALT', 'Altitude'),
  ('AMS', 'Amsterdam (Schiphol) Airport'),
  ('AOC', 'Air Operator Certificate'),
  ('APU', 'Auxiliary Power Unit'),
  ('ARBO', 'Arbeidsomstandigheden (Work and Environmental Act)'),
  ('ASA', 'Advanced Seat Assignment'),
  ('ASR', 'Air Safety Report'),
  ('ASU', 'Attendant Service Unit'),
  ('ATA', 'Actual Time of Arrival'),
  ('ATC', 'Air Traffic Control'),
  ('AVIH', 'Animal in Hold'),
  ('AXE', 'Axe'),
  ('BFK', 'Battery Fire Kit'),
  ('BSI', 'Boeing Sky Interior'),
  ('CAA-NL', 'Civil Aviation Authorities Netherlands'),
  ('CAO', 'Collectieve Arbeids Overeenkomst (Mutual Labor Agreement)'),
  ('CAS', 'Cabin Attendant Seat'),
  ('CAT', 'Clear Air Turbulence'),
  ('CBBG', 'Cabin baggage on additional seat'),
  ('CCM', 'Cabin Crew Member'),
  ('CCS', 'Center Ceiling Stowage (FWD, MID, AFT)'),
  ('CDLS', 'Cockpit Door Locking System'),
  ('CDSS', 'Cockpit Door Surveillance System'),
  ('CEC', 'Cabin Emergency Checklist'),
  ('CIDS', 'Cabin Intercommunication Data System'),
  ('CODL', 'Cabin Open Defect List'),
  ('COM', 'Cabin Operations Manual'),
  ('CRD', 'Child Restraint Device'),
  ('CRM', 'Crew Resource Management'),
  ('CSI', 'Cabin Safety Instructor'),
  ('CSM', 'Cabin Safety Manual'),
  ('CLV', 'Crew life vest'),
  ('CVR', 'Cockpit Voice Recorder'),
  ('DEPA', 'Deportee accompanied by escort'),
  ('DEPU', 'Deportee unaccompanied by escort'),
  ('DEMO', 'Demonstration kit (oxygen, belt, live vest & safety card)'),
  ('DG', 'Dangerous Goods'),
  ('DPNA', 'Passenger with intellectual or behavioral impairments'),
  ('EASA', 'European Aviation Safety Agency'),
  ('ED', 'Explosive Device'),
  ('ELT', 'Emergency Locator Transmitter'),
  ('ER', 'Escape Rope'),
  ('ERG', 'Emergency Response Guidance'),
  ('ERK', 'Emergency Response Kit'),
  ('ESAN', 'Emotional Support Animal'),
  ('ETA', 'Estimated Time Arrival'),
  ('FAK', 'First Aid Kit'),
  ('FAP', 'FWD Attendant Panel'),
  ('FAO2', 'First Aid Oxygen Bottle'),
  ('FDDAS', 'Flight Deck Door Access System'),
  ('F/O', 'First Officer'),
  ('FPG', 'Fire Proof Gloves'),
  ('FS', 'Flight Safety'),
  ('FTL', 'Flight Time Limitations'),
  ('GenDec', 'General Declaration'),
  ('GIF', 'General Information and Forms'),
  ('GPU', 'Ground Power Unit'),
  ('H2O', 'Water extinguisher'),
  ('HAL', 'Halotron Fire Extinguisher'),
  ('HIL', 'Hold Item List'),
  ('HV', 'Transavia (IATA)'),
  ('IED', 'Improvised Explosive Device'),
  ('IFL', 'Inspection Flashlight'),
  ('INAD', 'Inadmissible'),
  ('ILT', 'Inspectie Leefomgeving en Transport'),
  ('ISPSS', 'In Seat Power Supply System'),
  ('JAA', 'Joint Aviation Authorities'),
  ('JAR', 'Joint Aviation Requirements/Regulations'),
  ('LAV', 'Lavatory'),
  ('LI', 'Line Instructor'),
  ('LED', 'Light Emitting Diode'),
  ('LEP', 'List of Effective Pages'),
  ('LSU', 'Lavatory Service Unit'),
  ('LT', 'Local Time'),
  ('LV', 'Life Vest'),
  ('MEG', 'Megaphone'),
  ('MEK', 'Medical Emergency Kit'),
  ('MRT', 'Manual Release Tool'),
  ('NIL', 'No Items Listed (Nothing)'),
  ('NM', 'Nautical Miles'),
  ('O2', 'Oxygen, O2 mask (connected to FAO2)'),
  ('OCC', 'Operations Control Centre'),
  ('OHSC', 'Over Head Stowage Compartment (Hatrack)'),
  ('OM', 'Operations Manual'),
  ('OM-A', 'Operations Manual - Part A'),
  ('PA', 'Public Address'),
  ('PACO', 'Pantry - cabin code'),
  ('PAP', 'One passenger'),
  ('Part-OPS', 'European regulations for civil aviation'),
  ('PAX', 'More than one passenger'),
  ('PBE', 'Protective Breathing Equipment'),
  ('PED', 'Portable Electronic Device'),
  ('PETC', 'Pet in Cabin'),
  ('PDC', 'Passenger Distribution Card'),
  ('PF', 'Pilot Flying'),
  ('PIC', 'Pilot in Command'),
  ('PIL', 'Passenger Information List'),
  ('PPax', 'Pre-selected Passengers'),
  ('PNF', 'Pilot Non-Flying'),
  ('PNR', 'Passenger Name Record'),
  ('POR', 'Porto phone'),
  ('PRAM', 'Pre-recorded Announcement Machine'),
  ('PRAS', 'Pre-recorded Announcement System'),
  ('PRK', 'Passenger Restraint Kit'),
  ('PRM', 'Person with Reduced Mobility'),
  ('PSS', 'Pre-flight Security Search'),
  ('PSU', 'Passenger Service Unit'),
  ('QAL', 'Quick Access Light'),
  ('QDM', 'Quick Donning Mask'),
  ('QRH', 'Quick Reference Handbook'),
  ('RES', 'Spare (Res SB, Res LV, Res-O2)'),
  ('RFF', 'Rescue and Fire Fighting'),
  ('ROM', 'Route and airport instructions and information Manual'),
  ('SAR', 'Search and Rescue'),
  ('S&QA', 'Safety & Quality Assurance'),
  ('SB', 'Seatbelt'),
  ('SCCM', 'Senior Cabin Crew Member (Purser)'),
  ('SCD', 'Subject to Commanders Discretion'),
  ('SCP', 'Special Category of Passenger'),
  ('SG', 'Smoke goggles'),
  ('SIC', 'Safety Instruction Card'),
  ('SK', 'Survival Kit'),
  ('SOP', 'Standard Operating Procedures'),
  ('SPL', 'Schiphol Airport'),
  ('S&S', 'Sales and Service'),
  ('SSR', 'Special Service Request'),
  ('STA', 'Scheduled Time of Arrival'),
  ('SVAN', 'Service Animal'),
  ('TI', 'Temporary Instruction'),
  ('TO', 'Transavia France (IATA)'),
  ('TP', 'Technical Purser'),
  ('TR', 'Temporary Revision'),
  ('TRA', 'Transavia (ICAO)'),
  ('TUC', 'Time of Useful Consciousness'),
  ('UM', 'Unaccompanied Minor'),
  ('UPK', 'Universal Precaution Kit'),
  ('UTC', 'Universal Time Coordinated'),
  ('UN', 'United Nations'),
  ('VIP', 'Very Important Person'),
  ('VTZ', 'Flight Technical Affairs'),
  ('WCMP', 'Wheelchair Manual Powered'),
  ('WCLB', 'Wheelchair with Lithium Battery'),
  ('WCOB', 'On-Board Wheelchair'),
  ('WRR', 'Werk en Rusttijden Regeling (Work and Rest Regulations)')
ON CONFLICT (shortcut) DO NOTHING;